#pragma once
// 文件说明：
// ISqlDialect 处理不同数据库的 SQL 语法差异：
// 标识符引用、占位符风格（? vs $n）、自增列、类型名归一化等。

#include <string>
#include <memory>
#include <cctype>

namespace uORM {

enum class DialectKind {
    MySQL,
    PostgreSQL,
    SQLite
};

// SQL 方言接口
class ISqlDialect {
public:
    virtual ~ISqlDialect() = default;

    virtual DialectKind kind() const = 0;

    // 引用标识符 (MySQL: `col`，PG/SQLite: "col")
    virtual std::string quoteIdentifier(const std::string& id) const = 0;

    // 将统一占位符 ? 转换为方言原生风格（PG: $1, $2...；MySQL/SQLite: 保持 ?）
    virtual std::string convertPlaceholders(const std::string& sql) const { return sql; }

    // 归一化用户书写类型名（如 PG: DATETIME -> TIMESTAMP, DOUBLE -> DOUBLE PRECISION）
    virtual std::string normalizeTypeName(const std::string& type) const { return type; }

    // 自增列修饰符（MySQL: AUTO_INCREMENT，PG: GENERATED BY DEFAULT AS IDENTITY，SQLite: 特殊处理）
    virtual std::string getAutoIncrementModifier() const = 0;

    // 是否支持 INSERT ... RETURNING（PG / SQLite 3.35+）
    virtual bool supportsReturningId() const = 0;

    // 表选项（MySQL: ENGINE=InnoDB...，PG/SQLite: 空）
    virtual std::string getTableOptions(const std::string& defaultOptions) const = 0;

    // 旧接口兼容：获取最后插入 ID 的 SQL
    virtual std::string getLastInsertIdSql() const = 0;
};

// 占位符转换通用实现：跳过字符串字面量与引用标识符后，将 ? 替换为 $n
// 供 PostgreSQL 方言使用。
inline std::string placeholdersToDollar(const std::string& sql) {
    std::string out;
    out.reserve(sql.size() + 8);
    int n = 0;
    bool inSingle = false, inDouble = false;
    for (std::size_t i = 0; i < sql.size(); ++i) {
        char c = sql[i];
        if (inSingle) {
            out += c;
            if (c == '\'') {
                // '' 为转义的单引号
                if (i + 1 < sql.size() && sql[i + 1] == '\'') { out += '\''; ++i; }
                else inSingle = false;
            }
            continue;
        }
        if (inDouble) {
            out += c;
            if (c == '"') inDouble = false;
            continue;
        }
        if (c == '\'') { inSingle = true; out += c; continue; }
        if (c == '"') { inDouble = true; out += c; continue; }
        if (c == '?') { ++n; out += '$'; out += std::to_string(n); continue; }
        out += c;
    }
    return out;
}

// MySQL 方言实现
class MySQLDialect : public ISqlDialect {
public:
    DialectKind kind() const override { return DialectKind::MySQL; }
    std::string quoteIdentifier(const std::string& id) const override { return "`" + id + "`"; }
    std::string getAutoIncrementModifier() const override { return "AUTO_INCREMENT"; }
    bool supportsReturningId() const override { return false; }
    std::string getTableOptions(const std::string& defaultOptions) const override { return defaultOptions; }
    std::string getLastInsertIdSql() const override { return "SELECT LAST_INSERT_ID()"; }
};

// PostgreSQL 方言实现
class PostgreSQLDialect : public ISqlDialect {
public:
    DialectKind kind() const override { return DialectKind::PostgreSQL; }
    std::string quoteIdentifier(const std::string& id) const override { return "\"" + id + "\""; }
    std::string convertPlaceholders(const std::string& sql) const override { return placeholdersToDollar(sql); }
    std::string normalizeTypeName(const std::string& type) const override {
        // 归一化常见 MySQL 风格类型名到 PG 等价类型
        if (type == "DATETIME" || type == "DATETIME2") return "TIMESTAMP";
        if (type == "DOUBLE" || type == "DOUBLE PRECISION") return "DOUBLE PRECISION";
        if (type == "TINYINT(1)") return "BOOLEAN";
        if (type == "TINYINT") return "SMALLINT";
        if (type == "MEDIUMINT") return "INTEGER";
        if (type == "INT UNSIGNED") return "BIGINT";
        if (type == "BIGINT UNSIGNED") return "NUMERIC(20)";
        return type;
    }
    std::string getAutoIncrementModifier() const override { return "GENERATED BY DEFAULT AS IDENTITY"; }
    bool supportsReturningId() const override { return true; }
    std::string getTableOptions(const std::string&) const override { return ""; }
    std::string getLastInsertIdSql() const override { return "RETURNING id"; }
};

} // namespace uORM
