#pragma once 
#include <string> 

namespace uORM { 

// SQL 方言接口，处理不同数据库的 SQL 语法差异 
class ISqlDialect { 
public: 
    virtual ~ISqlDialect() = default; 
    
    // 获取类型对应的 SQL 字符串 (例如 INT vs INTEGER) 
    // 这里简单起见，可以结合 TypeMapping 使用，或者在此处做转换 
    // virtual std::string getTypeName(DataType type) = 0; 

    // 获取自增关键字 (MySQL: AUTO_INCREMENT, PG: SERIAL/GENERATED...) 
    // 注意：PG 的 SERIAL 是一种伪类型，通常在建表时指定类型，而 AUTO_INCREMENT 是属性。 
    // 这里我们返回用于建表列定义的修饰符。 
    virtual std::string getAutoIncrementModifier() const = 0; 

    // 判断是否需要 RETURNING id (PG 需要，MySQL 不需要) 
    virtual bool supportsReturningId() const = 0; 
    
    // 获取获取最后插入ID的 SQL (MySQL: SELECT LAST_INSERT_ID(), PG: RETURNING id) 
    virtual std::string getLastInsertIdSql() const = 0; 
    
    // 获取表引擎选项 (MySQL: ENGINE=InnoDB..., PG: 空) 
    virtual std::string getTableOptions(const std::string& defaultOptions) const = 0; 
    
    // 引用标识符 (MySQL: `col`, PG: "col") 
    virtual std::string quoteIdentifier(const std::string& id) const = 0; 
}; 

// MySQL 方言实现 
class MySQLDialect : public ISqlDialect { 
public: 
    std::string getAutoIncrementModifier() const override { return "AUTO_INCREMENT"; } 
    bool supportsReturningId() const override { return false; } 
    std::string getLastInsertIdSql() const override { return "SELECT LAST_INSERT_ID()"; } 
    std::string getTableOptions(const std::string& defaultOptions) const override { return defaultOptions; } 
    std::string quoteIdentifier(const std::string& id) const override { return "`" + id + "`"; } 
}; 

// PostgreSQL 方言实现 
class PostgreSQLDialect : public ISqlDialect { 
public: 
    std::string getAutoIncrementModifier() const override { 
        // PG 10+ 使用 GENERATED BY DEFAULT AS IDENTITY，旧版用 SERIAL 
        // 简单起见，假设用户在 FieldMeta 中如果不写类型，我们会追加此修饰符。 
        // 但通常 PG 中自增是类型 SERIAL，而不是 INT AUTO_INCREMENT。 
        // 这是一个差异点。uORM 的 FieldMeta 可能需要调整。 
        // 暂时返回空，假设用户在 PG 中使用 SERIAL 类型。 
        return ""; 
    } 
    bool supportsReturningId() const override { return true; } 
    std::string getLastInsertIdSql() const override { return "RETURNING id"; } 
    std::string getTableOptions(const std::string&) const override { return ""; } // PG 不支持 ENGINE=InnoDB 
    std::string quoteIdentifier(const std::string& id) const override { return "\"" + id + "\""; } 
}; 

} // namespace uORM 
